ADD_EVENT: str = '-ADD-'
ANOTHER_EVENT: str = '-ANOTHER-'
CANCEL_EVENT: str = '-CANCEL-'
ISSUES_EVENT: str = '-ISSUES-'
THEME_EVENT: str = '-THEME-'
RECORD_EVENT: str = '-RECORD-'
REMOVE_EVENT: str = '-REMOVE-'
RESTORE_EVENT: str = '-RESTORE-'
SAVE_EVENT: str = '-SAVE-'
SAVE_EVENTS: str = [SAVE_EVENT, ANOTHER_EVENT]
SETTINGS_EVENT: str = '-SETTINGS-'
START_UP_EVENT: str = '-START UP-'
SUBMIT_EVENT: str = '-SUBMIT-'
CLOSE_EVENT: str = '-CLOSE-'
WINDOW_CLOSED: str = None
WINDOW_CLOSE_ATTEMPTED_EVENT: str = '-WINDOW CLOSE ATTEMPTED-'
CLOSE_EVENTS = (CANCEL_EVENT, CLOSE_EVENT, WINDOW_CLOSED,
                WINDOW_CLOSE_ATTEMPTED_EVENT)
